-- Recreate schema sttt
DROP SCHEMA IF EXISTS sttt CASCADE;
CREATE SCHEMA sttt;

SET search_path TO sttt;

-- =========================
-- ENUMs
-- =========================

DROP TYPE IF EXISTS job_status CASCADE;
CREATE TYPE job_status AS ENUM ('pending', 'running', 'completed', 'error');

DROP TYPE IF EXISTS job_type CASCADE;
CREATE TYPE job_type AS ENUM ('transcribe', 'translate');

DROP TYPE IF EXISTS output_type CASCADE;
CREATE TYPE output_type AS ENUM ('text', 'srt');

-- =========================
-- 2) users
-- =========================
CREATE TABLE sttt.users (
  id              BIGSERIAL PRIMARY KEY,
  email           TEXT UNIQUE,
  display_name    TEXT,
  password_hash   TEXT NOT NULL, -- store bcrypt hash (not plaintext)

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- updated_at auto-update
CREATE OR REPLACE FUNCTION sttt.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON sttt.users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON sttt.users
FOR EACH ROW
EXECUTE FUNCTION sttt.set_updated_at();

-- Seed 1 user record (bcrypt hash should be generated by your app using bcrypt)
-- NOTE: Replace password_hash with a real bcrypt hash (usually starts with $2a$ / $2b$ / $2y$)
INSERT INTO sttt.users (email, display_name, password_hash)
VALUES ('admin@example.com', 'Admin', '$2b$12$5y/F/S7SI.7bVIh4mjccXuAt6KIODgFRtZGqHM9OYhn7n2MrUI.ha');

-- =========================
-- 3) jobs (job cha)
-- =========================
CREATE TABLE sttt.jobs (
  id                      BIGSERIAL PRIMARY KEY,

  user_id                 BIGINT NULL REFERENCES sttt.users(id) ON DELETE SET NULL,

  status                  sttt.job_status NOT NULL DEFAULT 'pending',

  total_children          INTEGER NOT NULL DEFAULT 0 CHECK (total_children >= 0),
  completed_children      INTEGER NOT NULL DEFAULT 0 CHECK (completed_children >= 0),

  error_message           TEXT NULL,

  type                    sttt.job_type NOT NULL,
  output_type             sttt.output_type NOT NULL,

  input_language          TEXT NOT NULL,
  output_language         TEXT NULL,

  transcribe_file_path    TEXT NULL,
  translate_file_path     TEXT NULL,

  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  metadata                JSONB NOT NULL DEFAULT '{}'::jsonb,

  CHECK (completed_children <= total_children)
);

DROP TRIGGER IF EXISTS trg_jobs_updated_at ON sttt.jobs;
CREATE TRIGGER trg_jobs_updated_at
BEFORE UPDATE ON sttt.jobs
FOR EACH ROW
EXECUTE FUNCTION sttt.set_updated_at();

CREATE INDEX idx_jobs_user_id ON sttt.jobs(user_id);
CREATE INDEX idx_jobs_status ON sttt.jobs(status);

-- =========================
-- 4) job_children (job con)
-- =========================
CREATE TABLE sttt.job_children (
  id                BIGSERIAL PRIMARY KEY,

  job_id            BIGINT NOT NULL REFERENCES sttt.jobs(id) ON DELETE CASCADE,

  input_file_path   TEXT NOT NULL,

  status            sttt.job_status NOT NULL DEFAULT 'pending',
  error_message     TEXT NULL,

  metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_job_children_updated_at ON sttt.job_children;
CREATE TRIGGER trg_job_children_updated_at
BEFORE UPDATE ON sttt.job_children
FOR EACH ROW
EXECUTE FUNCTION sttt.set_updated_at();

CREATE INDEX idx_job_children_job_id ON sttt.job_children(job_id);
CREATE INDEX idx_job_children_status ON sttt.job_children(status);
CREATE INDEX idx_job_children_metadata_gin ON sttt.job_children USING GIN (metadata);

-- =========================
-- 5) Trigger logic cập nhật job cha
-- =========================
CREATE OR REPLACE FUNCTION sttt.sync_parent_job_from_children(p_job_id BIGINT)
RETURNS VOID AS $$
DECLARE
  v_total        INTEGER;
  v_completed    INTEGER;
  v_has_error    BOOLEAN;
  v_first_err    TEXT;
  v_parent_status sttt.job_status;
BEGIN
  -- Lock job parent row
  SELECT status INTO v_parent_status
  FROM sttt.jobs
  WHERE id = p_job_id
  FOR UPDATE;

  -- Aggregate stats from children
  SELECT
    COUNT(*)::int,
    COUNT(*) FILTER (WHERE status = 'completed')::int,
    BOOL_OR(status = 'error'),
    (ARRAY_REMOVE(ARRAY_AGG(error_message ORDER BY updated_at DESC), NULL))[1]
  INTO
    v_total,
    v_completed,
    v_has_error,
    v_first_err
  FROM sttt.job_children
  WHERE job_id = p_job_id;

  -- Keep counters consistent
  UPDATE sttt.jobs
  SET
    total_children = COALESCE(v_total, 0),
    completed_children = COALESCE(v_completed, 0)
  WHERE id = p_job_id;

  -- Any child error => parent error + propagate message (if available)
  IF v_has_error THEN
    UPDATE sttt.jobs
    SET
      status = 'error',
      error_message = COALESCE(v_first_err, error_message)
    WHERE id = p_job_id;
    RETURN;
  END IF;

  -- All children completed => parent completed
  IF v_total > 0 AND v_completed = v_total THEN
    UPDATE sttt.jobs
    SET status = 'completed'
    WHERE id = p_job_id
      AND status IN ('pending', 'running');
    RETURN;
  END IF;

  -- Any child running => parent pending -> running (only if parent is pending)
  IF EXISTS (
    SELECT 1 FROM sttt.job_children
    WHERE job_id = p_job_id AND status = 'running'
  ) THEN
    UPDATE sttt.jobs
    SET status = 'running'
    WHERE id = p_job_id
      AND status = 'pending';
    RETURN;
  END IF;

  -- Otherwise keep parent status as-is.
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sttt.trg_job_children_sync_parent()
RETURNS TRIGGER AS $$
DECLARE
  v_job_id BIGINT;
BEGIN
  IF (TG_OP = 'DELETE') THEN
    v_job_id = OLD.job_id;
  ELSE
    v_job_id = NEW.job_id;
  END IF;

  PERFORM sttt.sync_parent_job_from_children(v_job_id);

  -- If job_id changed, sync old parent too
  IF (TG_OP = 'UPDATE') AND (OLD.job_id IS DISTINCT FROM NEW.job_id) THEN
    PERFORM sttt.sync_parent_job_from_children(OLD.job_id);
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_job_children_after_change ON sttt.job_children;
CREATE TRIGGER trg_job_children_after_change
AFTER INSERT OR UPDATE OR DELETE ON sttt.job_children
FOR EACH ROW
EXECUTE FUNCTION sttt.trg_job_children_sync_parent();